# Generated by Django 2.2.11 on 2020-03-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='name',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
